### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by futdev** [johhnybritain/ettercap-with-ping#2]
Anyway I can contact you? as appears you're no longer using twitter

**Comment by johhnybritain** [comment]
This email works

**Comment by futdev** [comment]
Hey man,

Any chance you'd be updating your ettercap system? I've got the GUI on 
my Mac & I'm unable to find a way to integrate a way of filtering Xbox 
One & adding the capability of showing the location etc..

**Comment by johhnybritain** [comment]
Not planning on doing any more work on it. Particularly since I bought a netduma gaming router which does all the Xbox traffic management, ping and geolocation stuff I had built into ettercap.

**Comment by futdev** [comment]
Hey man, I recently ordered the NetDuma after reading into it although I've noticed you don't get server IP's etc..? do you have a solution for this?
